[build]
  command = "pnpm run build"
  publish = "dist/spa"

[build.environment]
  VITE_PUBLIC_BUILDER_KEY = "695b5927986f48709c8c9f221b055aa4"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
